# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

anchors:
  email: &email "giulio@troccoli.it"
  github: &github "troccoli"
  twitter: &twitter "GiulioOfLondon"
  stackoverflow: &stackoverflow "1366144/giuliot"
  main_image: &main_image "/assets/images/hero.jpg"
  teaser_image: &teaser_image "/assets/images/hero500x300.jpg"

github: [metadata]
# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en_GB"
title                    : "Little pieces of (non)sense"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Giulio Troccoli-Allard"
description              : "Pieces of knowledge gathered during my years of working as a developer."
url                      : http://troccoli.it # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "troccoli/troccoli.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : *teaser_image # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
copyright                : # "copyright" name, defaults to site.title
copyright_url            : # "copyright" URL, defaults to site.url
comments:
  provider               : "staticman_v2"  # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    strict               : # 1 for enabled, 0 for disabled (default)
    input_position       : # "top", "bottom" # The comment input box will be placed above or below the comments
    emit_metadata        : # 1 for enabled, 0 for disabled (default) # https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#imetadatamessage
    lang                 : # "en" (default)
    lazy                 : # true, false # Loading of the comments will be deferred until the user scrolls near the comments container.
  staticman:
    allowedFields: ["name", "email", "url", "message"]
    branch: "master"
    commitMessage: "New comment"
    filename: "comment-{@timestamp}"
    format: "yaml"
    moderation: true
    path: "_data/comments/{options.slug}"
    requiredFields: ["name", "email", "message"]
    transforms:
      email: md5
    generatedFields:
      date:
        type: "date"
        options:
          format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
    endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey: "6LdMB0QUAAAAAP-4knv3ZhEZ5MH5hlh3k770ef1W"
  secret: "oHdy1lIgtXru0ioJ5j9AteVudzmhPyY8maOsN8cM1OtDUkYY4iSWMStc1fxUsYztBY7yWx3Erjg+Z5xhv5MBXTCJgAQCM8NXf0hgTKDsnOB2y0jwf3RAiMYQeolxEOuT5n7TuodR3SNI+3LKyaY6LPLuMWINpo66e+5RdU4Iezs="
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : # true, false (default)
algolia:
  application_id         : VHK0LDAGFB
  index_name             : 'posts'
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : *twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : *main_image # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Giulio Troccoli-Allard"
  avatar           : /assets/images/gravatar.jpeg # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Britalian, Olympic Drummer, mad baker and a bit of a geek (just a bit)"
  location         : "London, UK"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "http://troccoli.it"
    - label: "X"
      icon: "fab fa-fw fa-square-x-twitter"
      url: "https://twitter.com/GiulioOfLondon"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/troccoli"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url: "https://gitlab.com/{{ author.gitlab }}"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/1366144/giuliot"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "Keybase"
      icon: "fas fa-fw fa-key"
      # url: "https://keybase.io/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giulio-troccoli"
    - label: "XING"
      icon: "fab fa-fw fa-xing-square"
      # url: "https://www.xing.com/profile/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "Tumblr"
      icon: "fab fa-fw fa-tumblr-square"
      # url: "https://{{ author.tumblr }}.tumblr.com"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url: "https://bitbucket.org/{{ author.bitbucket }}"
    - label: "Last.fm"
      icon: "fab fa-fw fa-lastfm-square"
      # url: "https://last.fm/user/{{ author.lastfm }}"
    - label: "Dribbble"
      icon: "fab fa-fw fa-dribbble"
      # url: "https://dribbble.com/{{ author.dribbble }}"
    - label: "Pinterest"
      icon: "fab fa-fw fa-pinterest"
      # url: "https://www.pinterest.com/{{ author.pinterest }}"
    - label: "Foursquare"
      icon: "fab fa-fw fa-foursquare"
      # url: "https://foursquare.com/{{ author.foursquare }}"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      # url: "https://steamcommunity.com/id/{{ author.steam }}"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      # url: "https://www.youtube.com/user/{{ author.youtube }}"
    - label: "SoundCloud"
      icon: "fab fa-fw fa-soundcloud"
      # url: "https://soundcloud.com/{{ author.soundcloud }}"
    - label: "Weibo"
      icon: "fab fa-fw fa-weibo"
      # url: "https://www.weibo.com/{{ author.weibo }}"
    - label: "Flickr"
      icon: "fab fa-fw fa-flickr"
      # url: "https://www.flickr.com/{{ author.flickr }}"
    - label: "CodePen"
      icon: "fab fa-fw fa-codepen"
      # url: "https://codepen.io/{{ author.codepen }}"
    - label: "Vine"
      icon: "fab fa-fw fa-vine"
      # url: "https://vine.co/u/{{ author.vine }}"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/GiulioOfLondon"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/troccoli"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/1366144/giuliot"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giulio-troccoli"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .idea
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - docker-compose.yml
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - docs # ignore Minimal Mistakes /docs
  - test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/:name/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

resume:
  # Site Settings
  title: My Resume
  url: 'https://troccoli.it/resume/'
  baseurl: '/resume' #change it according to your repository name
  last_update: '11 July 2024'

  pdf: "troccoli-allard-resume-20240711.pdf"
  # Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
  style: orbit-6

  #Profile information
  name: "Giulio Troccoli-Allard"
  tagline: Senior Laravel Developer
  # place a 420x420 picture inside /assets/images/ folder and provide the name here (must be a JPG file)
  # Make sure you create a circle image as well, see https://www.gimp.org/tutorials/CircleImage/
  pic: "profile-photo-square.jpg"

  #sidebar links
  phone: "+447985197043"
  email: "giulio@troccoli.it"
  website: "troccoli.it"
  linkedin: "giulio-troccoli"
  github: "troccoli"
  twitter: "GiulioOfLondon"
  stackoverflow: "1366144/giuliot"
  #Update all the sections by editing the files inside _data folder.

  # Tracker
  analytics: #UA-83979019-1

  # Build settings
  encoding: "utf-8"
  compress_html: # - http://jch.penibelst.de/
    clippings: all
    ignore:
      envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      header:
        image: *main_image
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
